### ISSUE TITLE
Location of each cluster group

### ISSUE THREAD

**Issue by seacritasianman** [kwikteam/phy-contrib#100]
After I'm done clustering using template-gui, is there a way for me to pull out the depth info along with the corresponding group in matlab? i.e. is that info stored in one of the .npy files? Thanks!

**Comment by rossant** [comment]
This information is not saved at the moment, you can recreate it by looking at the template waveforms, taking the channel with the largest waveform amplitude, and retrieving the y component of the channel position.

**Comment by seacritasianman** [comment]
I tried loading the "templates.npy" into matlab which seem to contain the templates for each time point by channel. However, it seems to show perhaps the original 64 templates used to detect the spikes prior to manual curation and merging. Is this file supposed to be updated, or is there an updated file that I should be loading instead?

Thanks

**Comment by nsteinme** [comment]
This file is, as you say, the original templates used to detect spikes and
is not updated by manual curation. The spike_templates.npy file tells which
template detected each spike and is also not updated - only
spike_clusters.npy is updated to reflect your merges/splits. What you want
to do is figure out which template goes with your cluster of interested by
seeing which template number is most common among
spike_templates(spike_clusters==myClusterIndex). Since you will have merged
only very similar templates, taking the mode of that vector is sufficient,
but if you want to be very careful, the mean waveform will be closely
approximated by an average of the templates of each spike scaled by their
amplitudes. Or, you can always get the true mean waveform by using the
spike_times of the cluster and pulling the original spikes out of the
dataset to average together. hth,

Nick

**Comment by seacritasianman** [comment]
Hey, sorry to dig this up...

I've tried what you mentioned, and followed your steps. I'm able to isolate a template which is most common for the cluster of interest. However, when I then use that template number with templates.npy to find the channel whose template has the greatest amplitude, the channel number I'm getting through that process is not equivalent to the channel which template-gui tells me. 

If it helps, specifically, here are the steps I'm taking.
After isolating the mode of the vector (best_template),
I take the maximum value of the absolute value of each channel defined by the template across time (mean(abs(templates(best_template, :, i))), in a loop for each channel), then finding which channel gave me the max value. I then take that index and get the corresponding channel number from channel_map.npy, but that number does not correspond with the number that template-gui tells me. 

Thanks again for your help.

**Comment by seacritasianman** [comment]
I was able to solve the problem, it looks like my templates were offset by 1. Adding 1 to the template of interest fixed the problem. thanks!
