### ISSUE TITLE
Split clusters from WaveformView

### ISSUE THREAD

**Issue by nikolaskaralis** [kwikteam/phy-contrib#106]
It would be great if one could draw a polygon on the WaveformView as well.
There are some instances where the waveshapes are easily distinguishable (e.g. in the presence of noise).
In the example below, it would be very easy to capture the spikes that belong to the noise if we could draw the polygon in the Waveform View.
![screen shot 2017-03-28 at 15 59 07](https://cloud.githubusercontent.com/assets/4306518/24409103/829e665c-13cf-11e7-8a15-72d427b6a850.jpg)

**Comment by MS047** [comment]
Hello to all,

I agree, I would also find this option very practical. Maybe not a polygon, but a vertical bar for instance, allowing to separate unitary waveforms inside the vertical bar from those outside the bar.

I remember an issue where this question was asked, but @rossant answered that all this option was not implementable, I do not remember why, I think because the waveforms were not all displayed in waveform view.

Is this still true ? Maybe a solution has been found since ?

Thank you

**Comment by yger** [comment]
I may be wrong, but I'm pretty sure that Phy, because of speed and memory
consumption, is only showing a small sample of randomly chosen waveforms in
the WaveformView, for a given cluster. Therefore, drawing a polygon here to
select a subset makes no sense, as it will not be representative of the
whole cluster.

Le jeu. 27 avr. 2017 à 00:34, Maxime Beau <notifications@github.com> a
écrit :

**Comment by rossant** [comment]
> I may be wrong, but I'm pretty sure that Phy, because of speed and memory consumption, is only showing a small sample of randomly chosen waveforms in the WaveformView, for a given cluster. Therefore, drawing a polygon here to select a subset makes no sense, as it will not be representative of the whole cluster.

Indeed @yger !
