### ISSUE TITLE
Truncated amplitudes and weird Waveform view

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#109]
Since recently, we have a strange bug on one machine: the GUI is not displaying all amplitudes, and the Waveform view is also off, with waveforms far away from channel numbers, and weirdly displayed. The Traceview, however, is fine. See the attached image. Any idea about what could lead to only some amplitudes displayed, while all clusters have much more spikes? Maybe SpyKING CIRCUS is not exporting the data correctly, or could it be something related to numpy 1.12? (this is the only obvious difference that I can see between machines)

![bug_phy](https://cloud.githubusercontent.com/assets/1672447/25276494/caff5900-269a-11e7-9548-bf3b5e23bdda.png)

**Comment by BaptisteLefebvre** [comment]
Here are new insights about the "truncated amplitudes" issue. All the amplitudes are plotted but for some clusters the bounds used by the AmplitudeView limit the display of the amplitudes.

![2017_04_25_phy_truncated_amplitudes_issue_original](https://cloud.githubusercontent.com/assets/2544801/25374172/a28bd480-299c-11e7-9fc3-f311d8473dd8.png)

In this case, the data bounds of the AmplitudeView are equal to: (0.0, 0.0, **67.5**, 1.4018839597702026).

![2017_04_25_phy_truncated_amplitudes_issue_final](https://cloud.githubusercontent.com/assets/2544801/25374181/a94e4be0-299c-11e7-9ca0-4c2c196fba1b.png)

In this case, I have set manually the data bounds to: (0.0, 0.0, **14057.79345**, 1.4018839597702026) (in phycontrib/template/gui.py AmplitudeView._plot_points). I can now see all the amplitudes.

This "truncated amplitudes" issue occurred while using SpyKING-CIRCUS with **multiple** data files. When the TemplateModel is build (in phycontrib/template/model.py), the duration of the recording is computed based only on **one** data file.

A fix may be: instead of using the duration of the recording to define the data bounds of the AmplitudeView, use the last spike time to define these bounds (i.e. as when there is no data file available). (Additionally, if the length of the line in the AmplitudeView is unchanged, one will be able to see if there are spikes after the end of the recording.)

**Comment by nsteinme** [comment]
Just to add an opinion about the proposed fix, I recommend that time-axis
bounds of amplitude (and PC) views be the same for all clusters. So if you
define the bounds based on the last spike, make it the last spike of ALL
clusters, not just the currently selected cluster.

On Tue, Apr 25, 2017 at 9:19 AM, Baptiste Lefebvre <notifications@github.com

**Comment by BaptisteLefebvre** [comment]
Good point. Finally I found another solution. When SpyKING-CIRCUS launch Phy while dealing with multiple files, the ``DATAPATH`` variable (see code below) is equal to the name of only one file. If I set it equal to the concatenation of the names of all the files (separated by spaces) then the "truncated amplitudes" issue disappears.

```
gui_params                   = {}
gui_params['dat_path']       = DATAPATH
[...]

create_app()
controller = TemplateController(**gui_params)
```
