### ISSUE TITLE
WaveformView stacking all my channels

### ISSUE THREAD

**Issue by seacritasianman** [kwikteam/phy-contrib#116]
Hello, I previously used template-gui with a 1x8 configuration, and it worked well. Now, I'm using an 8x8 probe (64 total channels) and trying to spike sort this via kilosort, then template-gui. I'm having issues with waveform view, it seems to overlay all my channels on top of one another. I assume this is an issue with the channel map data or something, as it was working fine before (1x8 config), and the only changes I've made were: 1) updating the channel map and 2) increasing the templates from 32 to 128. Attached is a screenshot of the problem, note the waveform view being all stacked, and my channel map is pasted below: 

function make_ChannelMap_A64_8x8(fpath)

chanMap = [8:-1 :1,16:-1 :9,24:-1 :17,32:-1 :25,40:-1 :33,48:-1 :41,56:-1 :49,64:-1 :57];

connected = true(64, 1);

xcoords = 100 * [repmat(1,[1 8]) repmat(2,[1 8]) repmat(3,[1 8]) repmat(4,[1 8]) repmat(5,[1 8])...
     repmat(6,[1 8]) repmat(7,[1 8]) repmat(8,[1 8])]; 

ycoords = 100* repmat([0 1 2 3 4 5 6 7],[1,8]); 
ycoords = -ycoords;

kcoords = [repmat(1,[1 8]) repmat(2,[1 8]) repmat(3,[1 8]) repmat(4,[1 8]) repmat(5,[1 8])...
     repmat(6,[1 8]) repmat(7,[1 8]) repmat(8,[1 8])];

fs = 20000;

save(fullfile(fpath, 'chanMap.mat'), 'chanMap', 'connected', 'xcoords', 'ycoords', 'kcoords', 'fs')

![capture](https://user-images.githubusercontent.com/20893542/27803814-4ee68936-5fe0-11e7-88c6-1cce3a1b4655.PNG)

**Comment by maimechevee** [comment]
Hi, 
did you or anyone else ever solved that issue? It was working just fine and suddenly became overlaid, so I imagine I did something wrong in the gui/visualization..? Thanks!

**Comment by nsteinme** [comment]
In the screenshot from the original post, it looks like the waveforms aren't exactly overlapping, they are just mostly overlapping. This suggests that it can be fixed by scaling them way down - something like ctrl+left arrow a bunch of times, or other of the options in the waveform view menu.

**Comment by nsteinme** [comment]
or, it's just a bug that happens on july 3 each year ;)

**Comment by fjflores** [comment]
Hi: 

I have the same issue, and scaling does not work.  Please let us know if you guys are aware of a solution, or if it is a question for the phy team.

Cheers,

**Comment by nsteinme** [comment]
I think usually a zooming issue. Try zooming out, using many repeats of the
hotkeys like ctrl+left arrow (see dropdown menu for waveform view for
more). @rossant, could be a good idea to have a "reset view defaults"
option available, other than finding and deleting the ~/.phy folder?

**Comment by fjflores** [comment]
Got it. The many repeats of ctrl+left arrow and ctrl+up arrow finally did the trick. Thanks!

**Comment by DemetrisS** [comment]
Just to say that I have had the same issue but no matter how many "ctrl + left" etc I do, it does not resolve it.

I have 24 channels that are all arranged in a linear array so my channel map is very simple (and hasnt changed since everything was working ok). Indeed, when I re-open previous sessions that I had already processed (when everything working normally) the same issue happens again.

Attached is a snip showing how it looks for me (WaveformView has been setup to show mean waveforms as otherwise in this state it is too messy to make any sense).

If anyone has any other suggestions to try I would be very grateful. Also if any further info is needed just let me know.

Many thanks,
Demetris

![kilosort2](https://user-images.githubusercontent.com/43139278/45300290-d6eb2a00-b505-11e8-93da-87f409a5f48d.PNG)

**Comment by brendonw1** [comment]
Are you sure those are mean waveforms?  Those look like non-mean waveforms
with multiple noisy waveforms superimposed onto the more typical versions
of each waveform.  Sometimes there are noise events picked up and of course
are therefore superimposed.  Could that be it?

**Comment by DemetrisS** [comment]
Hi Brendon

That's a fair point and indeed (previously) I would also get some noise events in there.

I'm not sure that's the case here though because if I toggle between showing the mean and raw waveforms ('M' in the WaveformView panel) I get the attached image below and to me that seems like its all the waveforms for that 'id' and contacts superimposed together?  But unless I can separate them out by channel I can't really be sure what's what.

Many thanks,
Demetris

PS: the attached image is a snapshot of just one id, on the left with 'M' toggled and on the right with 'M' untoggled.

![graphic1](https://user-images.githubusercontent.com/43139278/45302944-81664b80-b50c-11e8-87fb-65569ae6b78f.jpg)

**Comment by DemetrisS** [comment]
SORTED

OK -   what sorted it for me was an excessively long  "shift-up".

Many thanks,
D

**Comment by brendonw1** [comment]
Awesome
