### ISSUE TITLE
A way to delete clusters in phy

### ISSUE THREAD

**Issue by madeleinea** [kwikteam/phy-contrib#122]
Rather than marking clusters as noise or MUA, it would be really helpful to be able to delete clusters in phy or from the spike_clusters.npy file. Is this a possibility?

**Comment by nsteinme** [comment]
I guess I use the "noise" label in this way. If I label it noise, I don't
later load them into my analysis code at all. Does that seem like a
workable solution? It's not clear what totally deleting it, as opposed to
labelling "noise", would gain you?

**Comment by madeleinea** [comment]
The problem is that when I split clusters in phy, it creates new clusters with IDs that go beyond the parameters of the template.npy file, which is what I've been using to identify the channel that is associated with each unit in my further analysis. I was hoping that by deleting clusters, the rest of the cluster IDs would become smaller and then fit into my template.npy parameters for identifying channels for each cluster.

**Comment by nsteinme** [comment]
The templates.npy matrix and the spike_templates.npy vector (identifying
the template that goes with each spike) are products of kilosort and will
never change with clustering. What you do when you manually sort is to make
a new file, spike_clusters.npy, which starts out identical to
spike_templates.npy but changes as you merge and split. When you merge two
units, the entries in spike_clusters for each of the spikes from those two
units will get replaced with a new number (higher than any existing number
so it doesn't conflict). Does that help, is it clearer now how you might
identify which template goes with a certain cluster, so that you can get
its peak channel? If you didn't see this documentation
<https://github.com/kwikteam/phy-contrib/blob/master/docs/template-gui.md>,
it might be helpful for understanding these concepts.

**Comment by nsteinme** [comment]
Since you're not the only one asking me about this stuff recently, I just added some more text to that documentation page, both describing these concepts as well as specifically addressing your question - see FAQ section. Let me know if that helps -
