### ISSUE TITLE
"Aborted!" error in cmd

### ISSUE THREAD

**Issue by shihaisun** [kwikteam/phy-contrib#137]
Hi all,

After calling template-gui through cmd (i.e. activate phy >> phy template-gui params.py) the line "Aborted!" comes up in the cmd. This file was working fine before and then I moved the folder to a different SSD storage on the same computer where this error occured. Would anyone happen to know how to fix this? 

Note: Template-gui works fine with other files in the SSD. 

Thank you,
Scott

**Comment by neuRowsATL** [comment]
Hi Scott,

I'm working on debugging a couple issues I've got myself (posted issue #139). So, in my digging I've become a little familiar with the several libraries that the Klusta Team have put together.

Can you provide a little more information about the error -- is there any other output that occurs between the "cmd >> phy template-gui params.py" and the "Aborted!" error?

**Comment by shihaisun** [comment]
Hi newRowsATL,

The only output the error gives after "phy template-gui params.py" is "Aborted!". I have attached a screenshot of the error below.

![image](https://user-images.githubusercontent.com/30403651/36651713-5e7f3cb0-1afe-11e8-9d9b-baf8e5302123.png)

Thanks,
Scott

**Comment by shihaisun** [comment]
Hi all,

I just got another one of my files producing an 'Aborted!' error. This time, I got the output leading up to the error. Does anyone know how to fix this?

![template gui error](https://user-images.githubusercontent.com/30403651/36777823-fb6cecd6-1cbe-11e8-8412-7845095954c4.PNG)

Thanks,
Scott

**Comment by neuRowsATL** [comment]
Hi Scott,

I was not able to find where the "Aborted" message is coming from after a quick search through the source code, so I'm not sure how far along the program gets before it runs into the error. When you successfully load the template-gui, do you get output, such as "Loading spike templates."? If so, this can help me to localize which function might be causing the problem. For example, with a successful load you get all the output, but in the case of this error there is no output at all, which means that the error is occurring BEFORE any of the functions that write out to the command line.

In any case, it looks like one of the data files is getting corrupted somehow. Based on the two screenshots you've provided it looks like the GUI might be corrupting the file when it updates the data file. I would start my debugging expedition by looking the data file that phy creates and saves to -- I use the kwik-gui and the data file I would go to first is the .kwik file.

Can you open a backup file from the original data that loaded successfully? I recommend making a copy of the backup file before trying to open it so that you can keep an uncorrupted version on hand.

**Comment by nsteinme** [comment]
Try deleting the ".phy" folder within the data directory and try again. This worked for someone else recently. If it works please let us know -
