### ISSUE TITLE
Channel reading as "dead" for some clusters in FeatureView

### ISSUE THREAD

**Issue by ereming** [kwikteam/phy-contrib#143]
I posted about this a while back (201704) in the phy-users Google group and just noticed that the issue still exists with Phy/KiloSort.

In the FeatureView, some channels have all zero amplitude values for features for a given cluster. See the amplitudes of PC1 & 2 for channel 21 for the red and blue clusters in the top image below. I'm sure it's not correct that for the blue and red clusters all of the events have zero amplitude.

I don't see any obvious pattern governing which channels are blanked out. There are also channels where it looks like some fraction of the events have been blanked - it just looks like there are *too many* zero amplitude events (see bottom image). Does anyone know what might be happening here? I'm clustering with KiloSort and using the template-gui.

![image](https://user-images.githubusercontent.com/8030712/37853420-067f9834-2ebd-11e8-9b3b-841c11a867b4.png)

![image](https://user-images.githubusercontent.com/8030712/37853423-0b9b0772-2ebd-11e8-8a1e-f80818c1ea70.png)

**Comment by nsteinme** [comment]
Sorry the issue didn't get a response previously.

Kilosort doesn't compute features for every spike for every channel. It
picks the top N channels for each template and computes the first P pc's
for each of those templates (where n=12 and p=3 by default, I think -
set-able in config). (this is so that the file size of the pc_features.npy
grows only with nspikes not with nspikes*nchannels). So that's why you see
zeros. I predict that when you see a single cluster that, for a single
channel, has some zero-value PCs and others not, it's because you merged
multiple templates, one or more of which were not computed for that channel
though others were. If you have a small number of channels, go ahead and
set it to compute pc's for every channel.

**Comment by ereming** [comment]
@nsteinme Thanks for the explanation! I will take another look.
