### ISSUE TITLE
phy template-gui params.py doesn't work

### ISSUE THREAD

**Issue by babaq** [kwikteam/phy-contrib#165]
Hi,

This is the first time I am trying to setup phy and template-gui. 
but after download example dataset and follow the instruction on phy and phy-contrib.

it says `"Error: No such command "template-gui".`

the phy command does hint with ` Add subcommands with plugins
  using "attach_to_cli()" and the "click" library.` what does this means?

am I missing something?

many thanks

**Comment by aliddell** [comment]
Check this thread: https://github.com/kwikteam/phy/issues/775
Then maybe this one: https://github.com/kwikteam/phy/issues/811

For me it was installing PyQt4 and tqdm.

**Comment by babaq** [comment]
Ok, according to @aliddell 's links, it seems that phy, and phy-contrib have some dependencies that's not listed in the `environment.yaml`, and even phy worked after manually installed some missing dependency, the template-gui won't report these dependencies, instead it will just complain the `template-gui` command doesn't exist.

one way to show missing dependency is ` python -c "import phy, phycontrib"`, then you'll be able to install all missing dependencies.

BTW, I am using a existing Anaconda distribution, not Miniconda.

Thanks @aliddell.

**Comment by aliddell** [comment]
Here's how I (finally) got Phy installed on Windows 10:

I used the following environment.yml file:
```yaml
name: phy
channels:
  - kwikteam
dependencies:
  - python
  - numpy=1.10
  - vispy
  - matplotlib
  - scipy
  - h5py
  - pyqt
  - requests
  - traitlets
  - six
  - joblib
  - click
  - tqdm
```

Modifications from that in phy-contrib are:
- numpy is now 1.10 instead of 1.09 (no ["missing 'stack'" error](https://github.com/kwikteam/phy-contrib/issues/134) because numpy.stack was introduced in 1.10
- don't install phy or klusta via pip; it installs phy in Anaconda3\Scripts, which you don't want.

Instead of using the command line, I used the Import button in Anaconda Navigator:
![image](https://user-images.githubusercontent.com/844464/54774272-b6e9a100-4be1-11e9-8c4f-d00d7246c9d8.png)
because when I used `conda env create -n phy` I got some guff about vs2015_runtime:

```
An error occurred while installing package 'conda-forge::vs2015_runtime-14.0.25420-0'.
```

Once I activated the phy environment (in anaconda-prompt, not in Powershell or CMD), I also had to install PyQt4 from a wheel build I found: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4

Finally, I installed the development phy and phy-contrib per the phy README:

`pip install git+https://github.com/kwikteam/phy git+https://github.com/kwikteam/phy-contrib --upgrade`

Now Phy is finally working!
