### ISSUE TITLE
What is template-feature view?

### ISSUE THREAD

**Issue by angelonc** [kwikteam/phy-contrib#171]
I imagine it is some projection that maximizes the distance between the selected clusters, but I can't find any documentation on it.

**Comment by nsteinme** [comment]
x-axis is the projection of every spike onto the blue neuron's template,
y-axis is the projection onto the red neuron. The difference between these
two projections defines kilosort's decision boundary which is why there
will always be a hard line there. To my understanding it does not take into
account the covariances of the clusters so it doesn't necessarily maximize
distance, but it will under the assumption that the whitening worked
perfectly, I guess.

**Comment by angelonc** [comment]
Great, thanks!
