### ISSUE TITLE
auto-select not just highest similarity score, but all with high similarity score and ACG==CCG

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#40]
Big picture idea: often there are several merges to make where the ACGs and CCG of the two clusters are all very similar. If we make a second similarity score that's about the ACG/CCG between a pair of templates (whether these three look the same), then we should just go ahead and select all units that score high on this, so you can merge them all at once. 

E.g. if there are three or more units like this, just show them all at once right away:
![image](https://cloud.githubusercontent.com/assets/7590975/14817644/65d47e30-0bb0-11e6-98cc-8490e4382418.png)

cc @kdharris101

**Comment by nsteinme** [comment]
Just another example of this:

![image](https://cloud.githubusercontent.com/assets/7590975/14817724/d62c3ec0-0bb0-11e6-8bef-44c1ad7e5084.png)

**Comment by yger** [comment]
I agree on the the fact that most obvious merges (when template
similarities are high and there is a clear dip in the CCG) should be done
quickly (if not automatically?), by at least suggested them to the user.
This is somehow similar to what we are currently doing with our
"meta-merging GUI", computing scores on ACG et CCG for all pairs of
neurons. However, in our case, this is done in a separate Python GUI, but
maybe this could be integrated into phy. I would be willing to do it, or at
least to export those scores if there is a proper way of handling them in
phy.

Best

Pierre

2016-04-26 14:14 GMT+02:00 nsteinme <notifications@github.com>:

**Comment by nsteinme** [comment]
Great! currently we have "similar_templates.npy", could we just write a new one with these scores called "similar_ccg.npy" or something? Is it slow to compute these, perhaps it could be a thing phy does upon opening if the file is not provided? 

Maybe the way it could work is that when you initiate the wizard on a cluster, it automatically selects any of the top 10 similar_templates score clusters that have a suitably high similar_ccg score? (if there are some outside of the top 10 you would get those after merging the current ones, then entering the wizard on the merged cluster).

**Comment by yger** [comment]
If you want to know more about what we are doing, have a look here

http://spyking-circus.readthedocs.org/en/latest/code/merging.html

In our case, we kept it separate from the main GUI because we viewed that
as an iterative process: you compute all those similarities scores for all
the pairs. Based on that, you do merges (a lot in a single click, see our
GUI), then we recompute all those scores, and the user iterates. In fact,
we can show than in only two or three iterations, you have almost done all
the "obvious" merges in your dataset. So this is way faster, and then you
only launch the GUI on that reduced datasets to you review the remaining
templates manually.

Drawbacks if that yes, those scores are not that fast to compute. If you
have 1000 templates, you have 1000**2 cross correlations to compute (you
can speed up in various ways, in our case we use MPI, but I guess GPU would
be better).

Pierre



2016-04-26 14:44 GMT+02:00 nsteinme <notifications@github.com>:

**Comment by nsteinme** [comment]
Thanks, I will try that out. Here is how I would speed up the CCG
computation: instead of computing 1000^2, just compute 1000*10 for the CCGs
between each neuron and its 10 most similar. Then compute others on the
fly...

**Comment by yger** [comment]
Ah ok, this makes perfect sense.

I guess this is a clever approach than my brute force method, even if I
would say that 10 may be too low. But still, the problem is that when you
do merges, you need to recompute everything, no? This can start to be
annoying if this is not performed in a separate step of the GUI, as it is
already slow enough...

Pierre

2016-04-26 15:26 GMT+02:00 nsteinme <notifications@github.com>:

**Comment by nsteinme** [comment]
I would say that after a merge you update the similar_templates without any
re-calculation, just taking the max between any constituent cluster and
each other. I.e. if you merge a and b then the similar_templates score for
[a,b] versus c should be the larger of the similar_templates score of a vs
c and b vs c. I believe this is what's currently done, I think it's just
fine.

Then you compute CCGs between the new spike train and the 10 (or 20,
whatever) most similar_templates. That is just 10 (or 20) new CCGs to
compute, that's all.

**Comment by rossant** [comment]
not sure if this is still needed with the latest versions of kilosort/spyking circus, feel free to reopen in the phy repo otherwise
