### ISSUE TITLE
important bug: merged clusters not being shown to similar clusters properly

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#41]
If you merge two clusters, these seem to stop appearing in the list of similar clusters for others. E.g. 

![image](https://cloud.githubusercontent.com/assets/7590975/14818571/c7c90f2a-0bb5-11e6-85fd-c9b6f1928611.png)

![image](https://cloud.githubusercontent.com/assets/7590975/14818629/0e30615c-0bb6-11e6-83bc-817c2a390cca.png)

Then I merge 441 and 1336, and when I select the new cluster (1770) I correctly see:

![image](https://cloud.githubusercontent.com/assets/7590975/14818676/4b328d82-0bb6-11e6-8459-6f83d544056c.png)

But if I select 185:

![image](https://cloud.githubusercontent.com/assets/7590975/14818692/61209bd4-0bb6-11e6-821c-27a518c444aa.png)

1770 should be in the list!! With a score of 0.931 (the max of its constituent templates against 185).

**Comment by mmyros** [comment]
Hello, this does not seem likely to be resolved soon, yet it cripples my workflow. @nsteinme have you found a workaround or have any pointers for fixing it? Thanks!

**Comment by nsteinme** [comment]
No I don't really have any workaround. Basically, if you know it's going to
happen, then I just be sure to make a decision, mua or good, about every
cluster that I merge before moving on to the next (so it doesn't matter
whether I see it again later). But I agree this is a poor solution for
several reasons.

@nippoo do you think you could take a look at this one? It is probably
relatively easy to fix I guess, if you know where to look for how it
decides what comes up in the similarity view. I had labeled it "important"
- which I still believe - and sounds like I am not the only one. I think
the solution is: each time there is a merge, construct a similar clusters
list for that new cluster as the maximum similarity score for each cluster
that was in the old two lists. THEN, add those new similarity scores into
the list of similar clusters of all others. If it is really a full
similarity matrix then this second step is just to make it symmetric.

**Comment by nippoo** [comment]
OK. This bug is because the "similarity" figure is pre-loaded from `similar_templates.npy`. This is pre-calculated in KiloSort by this function: https://github.com/cortex-lab/KiloSort/blob/556e5db8f95bc9e6b55d0def9c0e87c90f631e7c/fullMPMU.m#L56

I can't really figure out what this code is doing - perhaps @marius2p could shed some light?. In any case, the underlying reason is that *similarity scores are pre-loaded rather than being calculated on-the-fly* so that no generated / merged cluster will ever appear in the list, because these are statically loaded.

So the easy fix is to comment out lines 592-598 in gui.py (https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/template/gui.py#L592-L598), to use phy's default similarity algorithm (https://github.com/kwikteam/phy/blob/master/phy/cluster/manual/controller.py#L304-L323).

As you can see below, the similarity is slightly different and in different units:

**Kilosort similar_templates.npy**
<img width="611" alt="similar_templates.npy" src="https://cloud.githubusercontent.com/assets/1363114/15908521/142a2a7c-2dba-11e6-938d-0b7e21261891.png">

**phy similarity**
<img width="603" alt="phy similarity" src="https://cloud.githubusercontent.com/assets/1363114/15908522/142b5e74-2dba-11e6-8bd5-78ad73f8c953.png">

Is this acceptable for you, Nick? It doesn't seem to come with a noticeable speed hit, for me at least, though on first load it'll probably take a few seconds to calculate and memcache them. Is there something special about `similar_templates.npy`? (in KS or spyking_circus)? Either way, if you want to keep that similarity score rather than phy's, you'll have to tell me how to calculate it and reimplement it in the gui's similarity function.

**Comment by nsteinme** [comment]
No no no - sorry, I guess I didn't explain clearly!! It may be that the key
details were in an email with Cyrille or something. Yes there is something
special about similar_templates and we need to use those values. Phy just
needs to do something *mildly* clever when you make a merge: if you merge X
and Y, the similarity of new cluster Z with other cluster W should be the
maximum of X with W and Y with W.

Of course the confusing thing is that it will *already *show you *some* score
for W's similarity with Z - you see it right there in the similarity window
when you have Z selected. The confusing part is just that if you now go and
select W, Z does not show up in its list with *any* value, whether the
correct thing (max of X vs W and Y vs W) or anything else.

Does that make sense? Sorry...

**Comment by nippoo** [comment]
Ahhhhh sorry. Gotcha. Should have read your previous comment before writing.

So are you sure that you want it to take the maximum of the constituent templates' similarities (if you merge with a small cluster it could potentially skew the score?)? The simpler thing to do (and what's currently done in the other direction, if you select the new cluster) is to take the similarity from the "main template" ie the one which contributes the highest number of spikes to the cluster. So you wouldn't take the maximum of the two values in the case of a simple merge; you'd instead take the largest cluster's value. The solution you propose is a little more fiddly to implement and probably imperceptibly more computationally intensive (especially if you merge a cluster several times), but just let me know which one you think makes more sense.

**Comment by nsteinme** [comment]
Hi Max,

It needs to be the maximum of the two. Imagine a drifting neuron, you get
clusters 1, 2, 3, 4 which are all the same neuron but drifted. So 1 is
similar to 2, 2 to 3, 3 to 4, but 1 is not at all similar to 4. Now you
merge 1 and 2. If 1 happens to have more spikes than 2, you end up thinking
that 3 is not similar to the combined cluster, but you should think that.

Does it make sense? I definitely think that we need to use the maximum... I
can't imagine this is computationally intensive, that's absurd, there is
just one nClusters x nClusters similarity matrix and when you merge you're
just creating a new row as the max of two existing rows, no??

**Comment by nippoo** [comment]
OK! It's a little more subtle than this, actually. If you merge twice you have to take the max of three rows (etc etc). If you merge then split, you have to figure out whether the resultant clusters contain spikes from both/many templates, or one template, etc... Either way, there should be a way of generating this info from scratch rather than relying on a cached similarity matrix.

Anyway this is fine. I'll write a fix and submit a PR.

**Comment by nsteinme** [comment]
But just to be clear, the "not showing up in the list properly" is MUCH
more critical than "what *exactly* is the score and the ordering of the
list". If the scores aren't great, that's not the end of the world so long
as all the clusters actually get *in* the list so you will see it
eventually.

**Comment by nippoo** [comment]
OK. I haven't figured out a way of doing this quickly enough (i.e. the best I've managed is about 600ms every time you click on a cluster, which is too slow) without actually generating a similarity matrix on load and keeping it in memory. This isn't inherently a problem, but it's REALLY SLOW to generate the first time (like, a minute for 1000 clusters), and this means I need to keep track of all the merges and splits and update every time that happens. At least any way I've tried, which is probably not saying much...

@nsteinme can you think of a good way of generating this similarity matrix, given just the `similar_templates.npy` and list of templates for each cluster? The only way I can think of is first by iterating over each cluster, finding which templates correspond to each cluster (by looking up all the constituent spikes) - this takes 5-6 seconds to do on your dataset - then by iterating through each pair of clusters, slicing the `similar_templates` by the respective `constituent_cluster_ids` in `x` and `y`, and finding the max() of the resultant sliced array. This takes about 40 seconds on your dataset for my computer.

**Comment by nippoo** [comment]
FYI, I've got it fully working at about 4 milliseconds per cluster load for the 'main template' (this is stateless and so doesn't ever actually generate the similarity matrix, it just recalculates it at each load). This is in the PR.

And I've also got it working by taking the maximum, as you wanted (by generating the whole similarity matrix) but the code needs a bit more work to be robust when clusters get split or merged... so I'll probably attack this over the weekend.

**Comment by nippoo** [comment]
Oh, the ideal is, of course, if you can think of a reasonably efficient way of generating the similarity scores without having to generate and cache the whole matrix (just given `similar_templates.npy`). My `similarity` function (which takes around 500-600ms every time you click on a cluster, when you have 1000 clusters) looks like this:

```
    def get_cluster_template_sim(self, cluster_id):
        """
        Returns the similarity to every template for a given cluster.
        This function gets cached so takes only a millisecond or so every call.
        """
        cluster_templates = np.nonzero(self.get_cluster_templates(cluster_id))
        sims = self.similar_templates[:, cluster_templates]
        return np.amax(sims, axis=1)	

    def similarity(self, cluster_id):
        cluster_templates = np.nonzero(self.get_cluster_templates(cluster_id))
        sim = [[int(clu), np.max(self.get_cluster_template_sim(clu)[cluster_templates])] for clu in self.cluster_ids]
        return sim
```

If I can get this down to under 50ms, then there's no need to keep the whole similarity matrix updated / generate it initially, and deal with all that mess. :)

**Comment by rossant** [comment]
Hold on I will have a look this week end
I think I know how to fix this easily

**Comment by nippoo** [comment]
ok! p.s. I also fixed https://github.com/kwikteam/phy/blob/master/phy/cluster/manual/controller.py#L91 by simply updating those structures in the `on_update()` callback. but I'm not 100% sure that's all that's needed, since I think I'd need to selectively invalidate some caches...
