### ISSUE TITLE
documentation required: snippets, user_settings, phy_config

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#58]
1) A list of all snippets and a description of how to use them (Cyrille, I
went back to an old email where you had directed me how to find them, but
the links there are broken now)
2) A list of any parameters that can be set in a user_settings.py (is there
such a thing anymore?) and/or phy_config?

**Comment by nsteinme** [comment]
Also, link documentation from splash page of phy and phy-contrib.

**Comment by yger** [comment]
Do you mind if I could add also the procedure to launch the template GUI with SpyKING CIRCUS in the documentation, similarly to what you are doing with KiloSort? In fact, this is simpler, since you just need to do "circus-gui-python YOURDATA". But still, maybe this would be worth adding there, and not only on our doc.

**Comment by rossant** [comment]
documentation has been improved in the new version of phy
