### ISSUE TITLE
Sparse templates

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy-contrib#69]
Support sparse structures for templates.

@yger could you point me to a dataset generated by SpykingCircus with sparse templates, and explain me the data structure? Then I'll try to support that in phy.

**Comment by yger** [comment]
Yes, that would be great! I'm open to changes also, because currently as you can read here http://spyking-circus.readthedocs.io/en/latest/advanced/files.html our templates are saved in a .hdf5 format, and I know that you would prefer numpy arrays. 

But basically, what I am saving is simply a giant 2D matrix of size (N_e x N_t) x N_templates, if N_e is the number of channels, and N_t is the time width of the templates. Once you know that, this is easy to understand what I'm saving:
- the raw data (as temp_data)
- the non-zeros x indices (as temp_x)
- the non-zeros y indices (as temp_y)
- the shape (N_e, N_t, N_templates) (as temp_shape) (this is in fact rather redundant, since those parameters could be inferred from parameters, but well, at least this is self-contained)

Maybe there are more elegant solutions of doing that, but then, we can simply create T as a 2D sparse csr matrix with (temp_data, (temp_x, temp_y)), with shape as stated (N_e x N_t) x N_templates. Then, when you want to get a given template i, you simply need to do

T[:, i].asarray().reshape(N_e, N_t)

We can discuss that whenever you want to settle on an export format that you will find more elegant. You can save several numpy arrays, or maybe a .npz structure, I do not know

**Comment by rossant** [comment]
OK. Is there any reason why you don't save 3D arrays?

What about this structure:

```
templates.npy:          (n_templates, n_samples, n_channels_max)
templates_channels.npy: (n_templates, n_channels_max)
```

Would that work for you? I think it would be pretty simple for me to implement that.

**Comment by yger** [comment]
Well, yes, this can work. But as you are pointing out, this is suboptimal regarding disk usage, because if you have one template that is defined on all channels, then you do not gain anything. However, for us, such a situation should not happen, and n_channels_max will depend on the radius somehow, so it should be bounded. If this is easy to implement, then go for it.

**Comment by rossant** [comment]
Yes: if this is "good enough", I think we can start with this easier solution. If it's not, then we can implement something more efficient like your current solution.

What would be helpful for me is to obtain one of your datasets with this format implemented.

**Comment by yger** [comment]
Sure, I can provide you a dummy dataset, with only 32 channels: I'll send you an email asap. And then when this is working, I can scale you 4225 channels if you want to test scaling. But the key point, also, and I do not know how phy is handling datastructures, is that internally, you have to memmap such a datastructure to avoid keeping everything in memory: you only need to load templates that are needed

**Comment by rossant** [comment]
Sure, memmapping should be very easy with this structure.
