### ISSUE TITLE
select cluster from traceview

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#8]
If the unit color were in cluster view, it would facilitate matching up something in traceview with its cluster, e.g. when the list is sorted by depth. 

An even better solution would be a hotkey+click on traceview to select the unit of the nearest spike! Would that be possible?

**Comment by rossant** [comment]
So we're back to the one-color-per-cluster idea, right? :) I think we'd need to think this through...

No problem to select the unit of the nearest spike. I would prefer that solution. If you would too, maybe you can change the title of this issue.

**Comment by nsteinme** [comment]
Well you wouldn't need unique colors - the combination of color and probe depth could get you close - currently it's just that there are potentially a lot of units to click on (at roughly that depth) before you find the one (and each click is a little slow, of course). In any case, if the other solution is easy, it is better! Title changed.

**Comment by dzheezus** [comment]
Nick and Marius (Bauza, from O'Keefe lab) here. Marius had some additional thoughts about this: 

1) should be possible to either select the unit you click in an "override" fashion so that it becomes the only selected unit, OR to select it in addition to the one(s) already selected. I.e., if I have 500 and 501 selected, and I click a traceview spike of 503, do I now have 503 selected? or 500, 501, AND 503? Either should be possible. 

2) The reverse should also be possible - starting from a selected unit(s) and jumping to some window in traceview that contains that unit(s). I think we discussed that in some previous issue somewhere else?

3) What about an option to actually add the numerical labels of the cluster number to each spike shown in the traceview?

**Comment by rossant** [comment]
> 1) should be possible to either select the unit you click in an "override" fashion so that it becomes the only selected unit, OR to select it in addition to the one(s) already selected. I.e., if I have 500 and 501 selected, and I click a traceview spike of 503, do I now have 503 selected? or 500, 501, AND 503? Either should be possible.

* left click = just 503 selected
* ctrl+left click = 500, 501, and 503 selected

?

> 2) The reverse should also be possible - starting from a selected unit(s) and jumping to some window in traceview that contains that unit(s). I think we discussed that in some previous issue somewhere else?

yep

> 3) What about an option to actually add the numerical labels of the cluster number to each spike shown in the traceview?

sure

**Comment by nsteinme** [comment]
Yes that solution is perfect.

**Comment by rossant** [comment]
done
